version: '3'

services:
  github-user-viewer:
    build: .
    container_name: github-user-viewer
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - '.:/usr/app'
      - '/usr/app/node_modules'
